[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install --prefix client --include=optional",
  "npm install --prefix server"
]

[phases.build]
cmds = [
  "npm run build --prefix client",
  "npm run build --prefix server"
]

[start]
cmd = "npm start"
